(function(global){
const fallback="https://images.unsplash.com/photo-1583473848882-f9a5bc7fd2ee?auto=format&fit=crop&w=500&q=85";
const styles={
 boxer:{power:87,speed:94,chin:91,defense:95,iq:95,footwork:96,cardio:95,accuracy:95,aggression:82},
 puncher:{power:96,speed:89,chin:92,defense:87,iq:91,footwork:88,cardio:92,accuracy:92,aggression:95},
 pressure:{power:92,speed:90,chin:96,defense:87,iq:92,footwork:89,cardio:97,accuracy:91,aggression:98},
 counter:{power:90,speed:94,chin:91,defense:95,iq:97,footwork:95,cardio:94,accuracy:97,aggression:80},
 balanced:{power:91,speed:92,chin:92,defense:92,iq:93,footwork:92,cardio:94,accuracy:93,aggression:90}
};
const divisionWeights={Heavyweight:224,Cruiserweight:200,"Light Heavyweight":175,"Super Middleweight":168,Middleweight:160,"Junior Middleweight":154,Welterweight:147,"Junior Welterweight":140,Lightweight:135,"Junior Lightweight":130,Featherweight:126,"Junior Featherweight":122,Bantamweight:118,"Junior Bantamweight":115,Flyweight:112,"Junior Flyweight":108,Strawweight:105};
const heavyweightWeights={parker:255,zhang:291,kabayel:241,wardley:241,itauma:245,hrgovic:247,bakole:284};
const P=(opponent,result,note)=>({opponent,result,note});
const bestPerformances={
 parker:P("Deontay Wilder","UD 12","career-best late-prime control: calm defense, jab discipline and no panic against elite power"),
 zhang:P("Joe Joyce","TKO 6","southpaw heavyweight power statement: timing, size and repeated left hands broke a durable contender"),
 kabayel:P("Arslanbek Makhmudov","TKO 4","body-shot and angle upset that showed his pressure craft travels against bigger punchers"),
 ramirez:P("Arsen Goulamirian","UD 12","cruiserweight arrival: pace, southpaw volume and body work over a full title distance"),
 billamsmith:P("Lawrence Okolie","MD 12","career-defining title win built on pressure, knockdowns and ugly-range persistence"),
 cieslak:P("Ilunga Makabu","L 12","best high-level evidence: power and pressure held up against a proven cruiserweight champion"),
 benavidez:P("Caleb Plant","UD 12","elite pressure proof: slow-burn body work, volume and late-round damage against a slick boxer"),
 buatsi:P("Dan Azeez","UD 12","domestic elite control: cleaner fundamentals and physical strength over twelve"),
 yarde:P("Artur Beterbiev","L 8","best world-level showing despite defeat: speed and power created real danger"),
 mbilli:P("Sergiy Derevyanchenko","UD 10","pressure résumé stamp: sustained pace and body attack against elite experience"),
 pacheco:P("Marcelo Coceres","TKO 9","young contender statement: length, patience and late finishing at 168"),
 plant:P("José Uzcátegui","UD 12","title-winning boxer performance: movement, jab and composure against pressure"),
 alimkhanuly:P("Vincenzo Gualtieri","TKO 6","unification statement: southpaw control, power and clean finishing"),
 sheeraz:P("Austin Williams","TKO 11","breakout middleweight win: size, jab and late damage against an unbeaten contender"),
 adames:P("Julian Williams","TKO 9","physical middleweight pressure and power against a proven former champion"),
 madrimov:P("Magomed Kurbanov","TKO 5","title-level arrival: rhythm, athletic counters and finishing authority"),
 murtazaliev:P("Tim Tszyu","TKO 3","championship explosion: repeated power shots overwhelmed an elite contender"),
 fundora:P("Tim Tszyu","SD 12","bloody title upset: range, toughness and volume survived chaos"),
 ennis:P("Roiman Villa","KO 10","Boots at his most violent: switch-hitting layers, counters and a punishing finish"),
 stanionis:P("Radzhab Butaev","SD 12","high-pressure title win: volume, durability and inside exchanges"),
 barrios:P("Yordenis Ugás","UD 12","welterweight title-level proof: knockdowns, pace and clean punching"),
 haney:P("Regis Prograis","UD 12","best 140-lb control performance: jab, defense and clean scoring with no power illusion"),
 catterall:P("Josh Taylor","UD 12","career-defining revenge win: southpaw timing and disciplined counterpunching"),
 hitchins:P("Gustavo Lemos","UD 12","boxer-first title-level proof: jab, distance and survival under pressure"),
 zepeda:P("Maxi Hughes","TKO 4","lightweight volume pressure translated into clean, fight-ending momentum"),
 keyshawndavis:P("Gustavo Lemos","KO 2","breakout lightweight statement: speed, accuracy and sudden finishing"),
 andycruz:P("Brayan Zamarripa","UD 10","pro-style proof of amateur-class feet, counters and scoring control"),
 navarrete:P("Oscar Valdez","UD 12","awkward volume masterpiece against an elite Mexican rival"),
 foster:P("Rey Vargas","SD 12","title-winning defensive craft: counters, movement and late tactical clarity"),
 cacace:P("Joe Cordina","TKO 8","career-best upset: physical pressure and timing against an unbeaten champion"),
 espinoza:P("Robeisy Ramírez","MD 12","featherweight breakout: size, pace and late knockdown drama"),
 nickball:P("Ray Ford","SD 12","world-title breakthrough built on pressure, strength and relentless entries"),
 figueroa:P("Luis Nery","KO 7","pressure-fighter peak: body work, volume and finishing durability"),
 akhmadaliev:P("Daniel Roman","SD 12","title-winning all-action southpaw performance against a proven champion"),
 nery:P("Shinsuke Yamanaka","TKO 4","dangerous southpaw power peak, even with the controversy around the series"),
 picasso:P("Azat Hovhannisyan","UD 12","young contender proof: composure and volume against a rugged veteran"),
 nishida:P("Emmanuel Rodríguez","UD 12","bantamweight title win: southpaw distance and disciplined scoring"),
 tsutsumi:P("Takuma Inoue","UD 12","domestic title breakthrough with pressure and pace over twelve"),
 takei:P("Jason Moloney","UD 12","kickboxing-to-boxing proof: southpaw movement and title-level composure"),
 martinez:P("Kazuto Ioka","UD 12","unification-level pressure win with volume and physicality"),
 jefestrada:P("Román González","MD 12","elite little-man chess match: timing, counters and championship grit"),
 ioka:P("Kosei Tanaka","TKO 8","veteran masterclass: timing and counters broke a younger speed threat"),
 ayala:P("Dave Apolinario","KO 6","flyweight title statement: pressure and finishing power"),
 akui:P("Artem Dalakian","UD 12","flyweight title win built on volume and disciplined aggression"),
 gYafai:P("Sunny Edwards","TKO 6","breakout world-level pressure: strength, pace and physical command"),
 iwata:P("Jairo Noriega","TKO 3","junior-flyweight title statement with fast-start power"),
 nontshinga:P("Hector Flores","SD 12","title win: resilience, combinations and late-round grit"),
 ccanizales:P("Ryoichi Taguchi","UD 12","championship proof: pressure and consistency against an elite titlist"),
 jerusalem:P("Yudai Shigeoka","SD 12","strawweight title upset with timing and compact power"),
 taduran:P("Ginés Collado","TKO 12","pressure and southpaw attrition over the championship distance"),
 niyomtrong:P("Byron Rojas","UD 12","title-winning strawweight control with counters and balance"),
 wardley:P("Frazer Clarke","TKO 1","domestic heavyweight statement: immediate power and finishing instinct"),
 itauma:P("Mariusz Wach","TKO 2","young heavyweight proof: speed, calm and fast finishing against veteran size"),
 hrgovic:P("Zhilei Zhang","UD 12","best win: survived southpaw power and banked enough long-range work"),
 bakole:P("Jared Anderson","TKO 5","breakout heavyweight upset: pressure, size and heavy counters"),
 vergilortiz:P("Serhii Bohachuk","MD 12","elite fire-fight test: knockdowns survived, pressure and power sustained"),
 zayas:P("Patrick Teixeira","UD 10","prospect-to-contender step: jab, poise and distance control"),
 norman:P("Giovani Santillan","KO 10","welterweight arrival: timing, right hands and sudden finishing"),
 matias:P("Shohjahon Ergashev","RTD 5","pressure-fighter thesis: attrition, pace and breaking will"),
 mason:P("Yohan Vasquez","KO 2","lightweight prospect violence: southpaw speed and clean finishing"),
 carrington:P("Brandon Chambers","TKO 4","Shu Shu showcase: boxing craft, pressure and sharp finishing"),
 fulton:P("Brandon Figueroa","MD 12","elite 122-lb proof: inside craft and disciplined boxing under pressure"),
 nasukawa:P("Luis Robles","TKO 3","boxing transition statement: speed, timing and growing finishing confidence"),
 olascuaga:P("Riku Kano","KO 3","flyweight title puncher proof with fast, clean power"),
 takami:P("Toshiki Kawamitsu","TKO 8","junior-flyweight contender statement with pace and late damage"),
 matsumoto:P("Yuni Takada","UD 10","strawweight contender proof with sharp scoring and control")
};
const mk=(id,name,nickname,country,stance,division,rank,style="balanced",wiki=name)=>{
 const penalty=Math.min(4,(rank-1)*1.2),base=styles[style],ratings={};
 for(const [key,value] of Object.entries(base))ratings[key]=Math.round(Math.max(78,value-penalty));
 const ratingOverrides={
  haney:{power:76,aggression:76},
  hitchins:{power:77,aggression:74},
  andycruz:{power:76,aggression:72},
  catterall:{power:79},
  plant:{power:80}
 };
 Object.assign(ratings,ratingOverrides[id]||{});
 const last=name.split(" ").filter(part=>!["Jr.","Jr","Sr.","Sr","II","III","IV"].includes(part)).at(-1);
 return {id,name,last,nickname,country,stance,division,wiki,active:true,rankBaseline:rank,updated:"2026-07-08",years:[{year:2026,label:"CURRENT · JUL 2026",weight:heavyweightWeights[id]||divisionWeights[division],...ratings,bestPerformance:bestPerformances[id]}],img:fallback};
};
global.EXTRA_FIGHTERS.push(
 mk("parker","Joseph Parker","Lupesoliai La’auliolemalietoa","NZL","Orthodox","Heavyweight",3,"boxer"),
 mk("zhang","Zhilei Zhang","Big Bang","CHN","Southpaw","Heavyweight",4,"puncher"),
 mk("kabayel","Agit Kabayel","The Leberknocker","GER","Orthodox","Heavyweight",5,"pressure"),
 mk("ramirez","Gilberto Ramírez","Zurdo","MEX","Southpaw","Cruiserweight",1,"balanced","Gilberto Ramírez"),
 mk("billamsmith","Chris Billam-Smith","The Gentleman","GBR","Orthodox","Cruiserweight",2,"pressure"),
 mk("cieslak","Michał Cieślak","—","POL","Orthodox","Cruiserweight",6,"puncher","Michał Cieślak"),
 mk("benavidez","David Benavidez","The Mexican Monster","USA","Orthodox","Light Heavyweight",2,"pressure"),
 mk("buatsi","Joshua Buatsi","Just Business","GBR","Orthodox","Light Heavyweight",3,"balanced"),
 mk("yarde","Anthony Yarde","The Beast","GBR","Orthodox","Light Heavyweight",4,"puncher"),
 mk("mbilli","Christian Mbilli","Solide","FRA","Orthodox","Super Middleweight",1,"pressure"),
 mk("pacheco","Diego Pacheco","—","USA","Orthodox","Super Middleweight",3,"balanced"),
 mk("plant","Caleb Plant","Sweethands","USA","Orthodox","Super Middleweight",4,"boxer"),
 mk("alimkhanuly","Zhanibek Alimkhanuly","Qazaq Style","KAZ","Southpaw","Middleweight",1,"counter","Janibek Alimkhanuly"),
 mk("sheeraz","Hamzah Sheeraz","—","GBR","Orthodox","Middleweight",2,"puncher"),
 mk("adames","Carlos Adames","Caballo Bronco","DOM","Orthodox","Middleweight",3,"pressure"),
 mk("madrimov","Israil Madrimov","The Dream","UZB","Orthodox","Junior Middleweight",2,"balanced"),
 mk("murtazaliev","Bakhram Murtazaliev","—","RUS","Orthodox","Junior Middleweight",3,"puncher"),
 mk("fundora","Sebastian Fundora","The Towering Inferno","USA","Southpaw","Junior Middleweight",4,"pressure"),
 mk("ennis","Jaron Ennis","Boots","USA","Switch","Welterweight",1,"balanced"),
 mk("stanionis","Eimantas Stanionis","—","LTU","Orthodox","Welterweight",2,"pressure"),
 mk("barrios","Mario Barrios","El Azteca","USA","Orthodox","Welterweight",3,"balanced"),
 mk("haney","Devin Haney","The Dream","USA","Orthodox","Junior Welterweight",1,"boxer"),
 mk("catterall","Jack Catterall","El Gato","GBR","Southpaw","Junior Welterweight",2,"counter"),
 mk("hitchins","Richardson Hitchins","Africa","USA","Orthodox","Junior Welterweight",4,"boxer"),
 mk("zepeda","William Zepeda","Camaron","MEX","Southpaw","Lightweight",4,"pressure"),
 mk("keyshawndavis","Keyshawn Davis","The Businessman","USA","Orthodox","Lightweight",5,"balanced"),
 mk("andycruz","Andy Cruz","Diamante","CUB","Orthodox","Lightweight",9,"boxer","Andy Cruz (boxer)"),
 mk("navarrete","Emanuel Navarrete","Vaquero","MEX","Orthodox","Junior Lightweight",1,"pressure"),
 mk("foster","O'Shaquie Foster","Ice Water","USA","Orthodox","Junior Lightweight",2,"counter","O'Shaquie Foster"),
 mk("cacace","Anthony Cacace","The Apache","NIR","Southpaw","Junior Lightweight",3,"balanced"),
 mk("espinoza","Rafael Espinoza","El Divino","MEX","Orthodox","Featherweight",2,"pressure"),
 mk("nickball","Nick Ball","Wrecking Ball","GBR","Orthodox","Featherweight",3,"pressure"),
 mk("figueroa","Brandon Figueroa","The Heartbreaker","USA","Southpaw","Featherweight",6,"pressure"),
 mk("akhmadaliev","Murodjon Akhmadaliev","MJ","UZB","Southpaw","Junior Featherweight",2,"balanced"),
 mk("nery","Luis Nery","Pantera","MEX","Southpaw","Junior Featherweight",4,"puncher"),
 mk("picasso","Alan Picasso","Rey David","MEX","Orthodox","Junior Featherweight",5,"boxer"),
 mk("nishida","Ryosuke Nishida","—","JPN","Southpaw","Bantamweight",2,"boxer"),
 mk("tsutsumi","Seiya Tsutsumi","—","JPN","Orthodox","Bantamweight",3,"pressure"),
 mk("takei","Yoshiki Takei","—","JPN","Southpaw","Bantamweight",4,"puncher"),
 mk("martinez","Fernando Martínez","Pumita","ARG","Orthodox","Junior Bantamweight",1,"pressure","Fernando Martínez (boxer)"),
 mk("jefestrada","Juan Francisco Estrada","El Gallo","MEX","Orthodox","Junior Bantamweight",2,"counter"),
 mk("ioka","Kazuto Ioka","—","JPN","Orthodox","Junior Bantamweight",3,"balanced"),
 mk("ayala","Angel Ayala","Camaleon","MEX","Orthodox","Flyweight",1,"pressure"),
 mk("akui","Seigo Yuri Akui","—","JPN","Orthodox","Flyweight",3,"balanced"),
 mk("gYafai","Galal Yafai","—","GBR","Southpaw","Flyweight",4,"pressure"),
 mk("iwata","Shokichi Iwata","—","JPN","Orthodox","Junior Flyweight",2,"balanced"),
 mk("nontshinga","Sivenathi Nontshinga","The Special One","RSA","Orthodox","Junior Flyweight",3,"boxer"),
 mk("ccanizales","Carlos Cañizales","Triple C","VEN","Orthodox","Junior Flyweight",4,"pressure","Carlos Cañizales"),
 mk("jerusalem","Melvin Jerusalem","Gringo","PHI","Orthodox","Strawweight",1,"balanced"),
 mk("taduran","Pedro Taduran","Kid Pedro Heneral","PHI","Southpaw","Strawweight",2,"pressure"),
 mk("niyomtrong","Thammanoon Niyomtrong","Knockout CP Freshmart","THA","Orthodox","Strawweight",3,"counter"),
 mk("wardley","Fabio Wardley","—","GBR","Orthodox","Heavyweight",1,"puncher"),
 mk("itauma","Moses Itauma","—","GBR","Southpaw","Heavyweight",7,"balanced"),
 mk("hrgovic","Filip Hrgović","El Animal","CRO","Orthodox","Heavyweight",4,"balanced","Filip Hrgović"),
 mk("bakole","Martin Bakole","—","COD","Orthodox","Heavyweight",6,"pressure"),
 mk("vergilortiz","Vergil Ortiz Jr.","—","USA","Orthodox","Junior Middleweight",1,"pressure","Vergil Ortiz Jr."),
 mk("zayas","Xander Zayas","—","PUR","Orthodox","Junior Middleweight",5,"boxer"),
 mk("norman","Brian Norman Jr.","The Assassin II","USA","Orthodox","Welterweight",2,"puncher"),
 mk("matias","Subriel Matías","Browny","PUR","Orthodox","Junior Welterweight",2,"pressure","Subriel Matías"),
 mk("mason","Abdullah Mason","—","USA","Southpaw","Lightweight",6,"balanced"),
 mk("carrington","Bruce Carrington","Shu Shu","USA","Orthodox","Featherweight",6,"boxer"),
 mk("fulton","Stephen Fulton","Cool Boy Steph","USA","Orthodox","Featherweight",4,"boxer"),
 mk("nasukawa","Tenshin Nasukawa","—","JPN","Southpaw","Bantamweight",9,"boxer"),
 mk("olascuaga","Anthony Olascuaga","Princesa","USA","Orthodox","Flyweight",3,"puncher"),
 mk("takami","Kyosuke Takami","—","JPN","Orthodox","Junior Flyweight",4,"balanced"),
 mk("matsumoto","Ryusei Matsumoto","—","JPN","Orthodox","Strawweight",3,"balanced")
);
})(window);
