(function(global){
const fallback="https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png";
const styles={
 boxer:{power:86,speed:93,chin:89,defense:94,iq:94,footwork:95,cardio:94,accuracy:94,aggression:81},
 puncher:{power:95,speed:89,chin:91,defense:86,iq:90,footwork:87,cardio:91,accuracy:91,aggression:95},
 pressure:{power:91,speed:89,chin:95,defense:86,iq:91,footwork:88,cardio:97,accuracy:90,aggression:98},
 counter:{power:89,speed:93,chin:90,defense:94,iq:96,footwork:94,cardio:93,accuracy:96,aggression:79},
 balanced:{power:90,speed:91,chin:91,defense:91,iq:92,footwork:91,cardio:93,accuracy:92,aggression:89}
};
const divisionWeights={Heavyweight:224,Cruiserweight:200,"Light Heavyweight":175,"Super Middleweight":168,Middleweight:160,"Junior Middleweight":154,Welterweight:147,"Junior Welterweight":140,Lightweight:135,"Junior Lightweight":130,Featherweight:126,"Junior Featherweight":122,Bantamweight:118,"Junior Bantamweight":115,Flyweight:112,"Junior Flyweight":108,Strawweight:105};
const P=(opponent,result,note)=>({opponent,result,note});
const bestPerformances={
 spence:P("Kell Brook","KO 11","world-title breakthrough on the road: pressure, body work and late finishing"),
 ryangarcia:P("Devin Haney","MD 12","highest-profile win: speed, left-hook danger and multiple knockdowns"),
 frankmartin:P("Michel Rivera","UD 12","best boxing performance: southpaw timing, counters and clean control"),
 nahiralbright:P("Karlos Balderas","MD 8","career-best upset: toughness, composure and smart counters"),
 lamontroach:P("Héctor García","SD 12","title-level proof: patient boxing and clean late-round adjustments"),
 pitbullcruz:P("Rolly Romero","TKO 8","140-lb title breakthrough built on pressure and compact power"),
 rollyromero:P("Ismael Barroso","TKO 9","controversial but defining power comeback at world-title level"),
 josevalenzuela:P("Isaac Cruz","SD 12","career-best boxing discipline: southpaw movement and counter timing"),
 muratalla:P("Jeremiah Nakathila","TKO 2","lightweight contender statement with sharp power and fast finishing"),
 delossantos:P("José Valenzuela","KO 3","southpaw puncher proof with sudden, clean finishing danger"),
 schofield:P("René Téllez Girón","UD 12","young contender test: survived adversity and banked rounds"),
 hiraoka:P("Ismael Barroso","TKO 9","pressure and volume statement against a dangerous veteran puncher"),
 daltonsmith:P("Sam Maxwell","TKO 7","domestic contender statement: speed, timing and a highlight finish"),
 garyarussell:P("Viktor Postol","TKO 10","pressure-southpaw proof against an experienced former champion"),
 kennethsims:P("Elvis Rodríguez","MD 10","career-best upset: jab, composure and educated defense"),
 barboza:P("Jose Pedraza","UD 10","solid contender win with pressure, activity and clean boxing"),
 sandormartin:P("Mikey Garcia","MD 10","career-defining upset: southpaw movement and tactical discipline"),
 conorbenn:P("Chris Algieri","KO 4","welterweight puncher statement with explosive finishing"),
 alexisrocha:P("Blair Cobbs","KO 9","best win: southpaw pressure, body work and late stoppage"),
 santillan:P("Alexis Rocha","KO 6","career-best shocker: relentless pressure and heavy finishing"),
 polanco:P("Marcelino Lopez","UD 10","prospect proof: speed, clean combinations and controlled distance"),
 conwell:P("Juan Carlos Abreu","TKO 6","junior-middle contender statement with compact pressure"),
 lubin:P("Jeison Rosario","KO 6","comeback proof: southpaw power and body-shot finishing"),
 jesusramos:P("Joey Spencer","TKO 7","breakout pressure performance against an unbeaten prospect"),
 bohachuk:P("Brian Mendoza","UD 12","title-level pressure: pace, toughness and volume over twelve"),
 callumwalsh:P("Przemyslaw Runowski","KO 2","prospect statement with fast-start power and sharp finishing"),
 austinwilliams:P("Steve Rolls","UD 10","middleweight contender proof before the Sheeraz setback"),
 bentley:P("Marcus Morrison","TKO 4","domestic middleweight power and timing statement"),
 berlanga:P("Jason Quigley","UD 12","best extended test: knockdowns, stamina questions and power threat"),
 munguia:P("Sergiy Derevyanchenko","UD 12","elite action test: pressure, body work and late knockdown swing"),
 iglesias:P("Evgeny Shvedenko","KO 1","super-middleweight puncher statement with immediate finishing"),
 morrell:P("Yamaguchi Falcão","KO 1","explosive southpaw title-level statement"),
 khataev:P("Ricards Bolotniks","TKO 6","light-heavy contender proof with physical power"),
 albertramirez:P("Adam Deines","UD 10","southpaw contender control with range and pace"),
 riakhporhe:P("Krzysztof Głowacki","TKO 4","cruiserweight power statement against a former champion"),
 okolie:P("Krzysztof Głowacki","KO 6","world-title win built on reach, clinch control and right-hand power"),
 hunter:P("Martin Bakole","TKO 10","heavyweight upset built on speed, stamina and clean counters"),
 jaredanderson:P("Charles Martin","UD 10","prospect test: volume and composure through adversity"),
 ajagba:P("Stephan Shaw","UD 10","disciplined heavyweight boxing win after early-career volatility"),
 torrez:P("Brandon Moore","TKO 5","young heavyweight pressure and fast-handed finishing"),
 vianello:P("Arslanbek Makhmudov","TKO 8","career-best upset: size, jab and damage accumulation"),
 makhmudov:P("Carlos Takam","UD 10","best proven win: power threat maintained against a durable veteran")
};
const mk=(id,name,nickname,country,stance,division,level,style="balanced",wiki=name,active=true)=>{
 const penalty=Math.min(6,(level-1)*1.15),ratings={};
 for(const [key,value] of Object.entries(styles[style]))ratings[key]=Math.round(Math.max(77,value-penalty));
 const last=name.split(" ").filter(part=>!["Jr.","Jr","Sr.","Sr","II","III","IV"].includes(part)).at(-1);
 return {id,name,last,nickname,country,stance,division,wiki,active,updated:"2026-07-08",
  years:[{year:active?2026:2020,label:active?"CURRENT · JUL 2026":"CAREER VERSION",weight:divisionWeights[division],...ratings,bestPerformance:bestPerformances[id]}],img:fallback};
};
global.EXTRA_FIGHTERS.push(
 mk("spence","Errol Spence Jr.","The Truth","USA","Southpaw","Welterweight",1,"balanced","Errol Spence Jr."),
 mk("ryangarcia","Ryan Garcia","King Ry","USA","Orthodox","Junior Welterweight",2,"puncher"),
 mk("frankmartin","Frank Martin","The Ghost","USA","Southpaw","Lightweight",3,"counter","Frank Martin (boxer)"),
 mk("nahiralbright","Nahir Albright","Woo","USA","Orthodox","Lightweight",7,"boxer"),
 mk("lamontroach","Lamont Roach Jr.","The Reaper","USA","Orthodox","Lightweight",2,"counter","Lamont Roach Jr."),
 mk("pitbullcruz","Isaac Cruz","Pitbull","MEX","Orthodox","Junior Welterweight",3,"pressure","Isaac Cruz (boxer)"),
 mk("rollyromero","Rolando Romero","Rolly","USA","Orthodox","Welterweight",4,"puncher","Rolando Romero"),
 mk("josevalenzuela","José Valenzuela","Rayo","USA","Southpaw","Junior Welterweight",4,"counter","José Valenzuela (boxer)"),
 mk("muratalla","Raymond Muratalla","Danger","USA","Orthodox","Lightweight",2,"balanced"),
 mk("delossantos","Edwin De Los Santos","La Granada","DOM","Southpaw","Lightweight",4,"puncher"),
 mk("schofield","Floyd Schofield","Kid Austin","USA","Orthodox","Lightweight",5,"balanced"),
 mk("hiraoka","Andy Hiraoka","Da Blade","JPN","Southpaw","Junior Welterweight",4,"pressure"),
 mk("daltonsmith","Dalton Smith","Thunder","GBR","Orthodox","Junior Welterweight",3,"balanced"),
 mk("garyarussell","Gary Antuanne Russell","The Last","USA","Southpaw","Junior Welterweight",3,"pressure"),
 mk("kennethsims","Kenneth Sims Jr.","Bossman","USA","Orthodox","Junior Welterweight",6,"boxer"),
 mk("barboza","Arnold Barboza Jr.","—","USA","Orthodox","Junior Welterweight",3,"boxer","Arnold Barboza Jr."),
 mk("sandormartin","Sandor Martín","Arrasandor","ESP","Southpaw","Junior Welterweight",5,"counter","Sandor Martín"),
 mk("conorbenn","Conor Benn","The Destroyer","GBR","Orthodox","Welterweight",3,"pressure"),
 mk("alexisrocha","Alexis Rocha","Lex","USA","Southpaw","Welterweight",5,"pressure"),
 mk("santillan","Giovani Santillan","Gallo de Oro","USA","Southpaw","Welterweight",6,"pressure"),
 mk("polanco","Rohan Polanco","—","DOM","Orthodox","Welterweight",7,"balanced"),
 mk("conwell","Charles Conwell","Bad News","USA","Orthodox","Junior Middleweight",3,"balanced"),
 mk("lubin","Erickson Lubin","The Hammer","USA","Southpaw","Junior Middleweight",4,"puncher"),
 mk("jesusramos","Jesus Ramos Jr.","Mono","USA","Southpaw","Junior Middleweight",5,"pressure"),
 mk("bohachuk","Serhii Bohachuk","El Flaco","UKR","Orthodox","Junior Middleweight",3,"pressure"),
 mk("callumwalsh","Callum Walsh","King","IRL","Southpaw","Junior Middleweight",6,"balanced"),
 mk("austinwilliams","Austin Williams","Ammo","USA","Southpaw","Middleweight",5,"puncher","Austin Williams (boxer)"),
 mk("bentley","Denzel Bentley","2 Sharp","GBR","Orthodox","Middleweight",5,"puncher"),
 mk("berlanga","Edgar Berlanga","The Chosen One","PUR","Orthodox","Super Middleweight",4,"puncher"),
 mk("munguia","Jaime Munguía","—","MEX","Orthodox","Super Middleweight",3,"pressure","Jaime Munguía"),
 mk("iglesias","Osleys Iglesias","El Tornado","CUB","Southpaw","Super Middleweight",4,"puncher"),
 mk("morrell","David Morrell Jr.","Osvary","CUB","Southpaw","Light Heavyweight",2,"balanced","David Morrell (boxer)"),
 mk("khataev","Imam Khataev","—","RUS","Orthodox","Light Heavyweight",5,"puncher"),
 mk("albertramirez","Albert Ramírez","—","VEN","Southpaw","Light Heavyweight",6,"balanced","Albert Ramírez (boxer)"),
 mk("riakhporhe","Richard Riakporhe","The Midnight Train","GBR","Orthodox","Cruiserweight",4,"puncher"),
 mk("okolie","Lawrence Okolie","The Sauce","GBR","Orthodox","Heavyweight",5,"puncher"),
 mk("hunter","Michael Hunter","The Bounty","USA","Orthodox","Heavyweight",6,"boxer","Michael Hunter (boxer)"),
 mk("jaredanderson","Jared Anderson","The Real Big Baby","USA","Orthodox","Heavyweight",5,"pressure"),
 mk("ajagba","Efe Ajagba","The Silent Roller","NGA","Orthodox","Heavyweight",6,"puncher"),
 mk("torrez","Richard Torrez Jr.","Kiki","USA","Southpaw","Heavyweight",7,"pressure","Richard Torrez Jr."),
 mk("vianello","Guido Vianello","The Gladiator","ITA","Orthodox","Heavyweight",7,"balanced"),
 mk("makhmudov","Arslanbek Makhmudov","Lion","CAN","Orthodox","Heavyweight",7,"puncher"),
 mk("thurman","Keith Thurman","One Time","USA","Orthodox","Welterweight",2,"puncher","Keith Thurman",false),
 mk("porter","Shawn Porter","Showtime","USA","Orthodox","Welterweight",2,"pressure","Shawn Porter",false),
 mk("dannygarcia","Danny García","Swift","USA","Orthodox","Welterweight",2,"counter","Danny García",false),
 mk("kellbrook","Kell Brook","Special K","GBR","Orthodox","Welterweight",2,"balanced","Kell Brook",false),
 mk("broner","Adrien Broner","The Problem","USA","Orthodox","Welterweight",3,"counter","Adrien Broner",false)
);
})(window);
