(function(global){
global.RINGSIDE_UPCOMING_FIGHTS=[
 {
  id:"roach-zepeda-2026-08-01",
  eventName:"WBC Lightweight Title Card",
  fightDate:"2026-08-01",
  venue:"Las Vegas",
  promoter:"Golden Boy / DAZN",
  broadcast:"DAZN",
  boutOrder:1,
  red:"lamontroach",
  blue:"zepeda",
  redName:"Lamont Roach Jr.",
  blueName:"William Zepeda",
  division:"Lightweight",
  scheduledRounds:12,
  status:"scheduled",
  sourceCheckedAt:"2026-07-29",
  expiresAt:"2026-08-02",
  refreshCadence:"weekly",
  cardNote:"Source checked July 29, 2026. Title-fight preview built from the current schedule board.",
  market:{"label":"Style market","angle":"Roach's craft, resets and counter timing versus Zepeda's pressure volume"},
  sources:[{label:"Bad Left Hook schedule",url:"https://www.badlefthook.com/boxing-schedule"}]
 },
 {
  id:"ryangarcia-conorbenn-2026",
  eventName:"Welterweight Grudge Fight",
  fightDate:null,
  venue:"Venue TBA",
  promoter:"TBA",
  broadcast:"TBA",
  boutOrder:1,
  red:"ryangarcia",
  blue:"conorbenn",
  redName:"Ryan Garcia",
  blueName:"Conor Benn",
  division:"Welterweight",
  scheduledRounds:12,
  status:"scheduled",
  sourceCheckedAt:"2026-07-29",
  expiresAt:"2026-08-12",
  refreshCadence:"weekly",
  cardNote:"Source checked July 29, 2026. Exact fight-night details should be confirmed before publishing as locked.",
  market:{"label":"Style market","angle":"Garcia's trigger-speed left hook against Benn's pressure, pace and finishing intent"},
  sources:[{label:"ESPN schedule",url:"https://www.espn.com/boxing/story/_/id/12508267/boxing-fight-schedule"}]
 },
 {
  id:"canelo-mbilli-2026",
  eventName:"Super Middleweight Feature",
  fightDate:null,
  venue:"Venue TBA",
  promoter:"TBA",
  broadcast:"TBA",
  boutOrder:1,
  red:"canelo",
  blue:"mbilli",
  redName:"Saúl Álvarez",
  blueName:"Christian Mbilli",
  division:"Super Middleweight",
  scheduledRounds:12,
  status:"scheduled",
  sourceCheckedAt:"2026-07-29",
  expiresAt:"2026-08-12",
  refreshCadence:"weekly",
  cardNote:"Source checked July 29, 2026. Schedule-board preview; confirm sanctioning and final date before treating as locked.",
  market:{"label":"Style market","angle":"Canelo's counters, body reads and composure versus Mbilli's pressure pace"},
  sources:[{label:"ESPN schedule",url:"https://www.espn.com/boxing/story/_/id/12508267/boxing-fight-schedule"}]
 },
 {
  id:"daltonsmith-puello-2026",
  eventName:"Junior Welterweight Title-Level Preview",
  fightDate:null,
  venue:"Venue TBA",
  promoter:"TBA",
  broadcast:"TBA",
  boutOrder:2,
  red:"daltonsmith",
  blue:"albertopuello",
  redName:"Dalton Smith",
  blueName:"Alberto Puello",
  division:"Junior Welterweight",
  scheduledRounds:12,
  status:"scheduled",
  sourceCheckedAt:"2026-07-29",
  expiresAt:"2026-08-12",
  refreshCadence:"weekly",
  cardNote:"Source checked July 29, 2026. Add Alberto Puello to the roster to make this card playable.",
  market:{"label":"Style market","angle":"Smith's timing and domestic momentum versus Puello's southpaw range craft"},
  sources:[{label:"ESPN schedule",url:"https://www.espn.com/boxing/story/_/id/12508267/boxing-fight-schedule"}]
 },
 {
  id:"muratalla-cruz-2026",
  eventName:"Lightweight Contender Preview",
  fightDate:null,
  venue:"Venue TBA",
  promoter:"TBA",
  broadcast:"TBA",
  boutOrder:3,
  red:"muratalla",
  blue:"andycruz",
  redName:"Raymond Muratalla",
  blueName:"Andy Cruz",
  division:"Lightweight",
  scheduledRounds:12,
  status:"scheduled",
  sourceCheckedAt:"2026-07-29",
  expiresAt:"2026-08-12",
  refreshCadence:"weekly",
  cardNote:"Source checked July 29, 2026. Add Andy Cruz to the roster to make this card playable.",
  market:{"label":"Style market","angle":"Muratalla's pro pressure and punch placement versus Cruz's amateur-school distance and angles"},
  sources:[{label:"ESPN schedule",url:"https://www.espn.com/boxing/story/_/id/12508267/boxing-fight-schedule"}]
 }
];
})(window);
